### ISSUE TITLE
Correct time command

### ISSUE THREAD

**Issue by TheOtherUnknown** [TheOtherUnknown/Malcolm-next#11]
The time command in the timezone branch has a few issues that need to be addressed before it can be merged to master:
* Help text is missing
* The command is only responding with Zulu time, no matter the input (See image) 
![image](https://user-images.githubusercontent.com/15039983/107266280-45a07a80-6a13-11eb-866b-2f960198379c.png)
Finally, I thought this command was supposed to actually convert times? Not just be a world clock. I guess that's up to what the server wants.

**Comment by TheOtherUnknown** [comment]
@marvelman3284  This now fails with this command: `,time 3:00PM EST CET`
Exception:
```
Traceback (most recent call last):
  File "/home/adam/.local/share/virtualenvs/Malcolm-next-EDaiGMpS/lib/python3.9/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/adam/Desktop/dev/Malcolm-next/src/cogs/utils.py", line 224, in time
    local = datetime(int(y), int(m_), int(d), int(h), int(m))
ValueError: invalid literal for int() with base 10: '00PM'
```

**Comment by jeevanshah07** [comment]
As for right know I don't have AM/PM implemented. That's why you are getting the error.
