### ISSUE TITLE
Antispam: Ban new users that spam links

### ISSUE THREAD

**Issue by TheOtherUnknown** [TheOtherUnknown/Malcolm-next#31]
We've been seeing an increase in unverified, but not necessarily newly joined accounts spraying all channels with links. 

It would be great if we could prevent that via Malcom.

**Comment by Sufferous** [comment]
Would you still like this done?

**Comment by jeevanshah07** [comment]
Sure!

**Comment by TheOtherUnknown** [comment]
Resolved by Discord automod, no longer needed
